"use client";

import { useState } from "react";
import type { CampaignData, PlanData } from "@/app/page";
import { FileDown, ClipboardCheck, Clipboard, Printer } from "lucide-react";

interface Props {
  campaign: CampaignData | null;
  plan: PlanData | null;
}

function buildMarkdown(campaign: CampaignData | null, plan: PlanData | null): string {
  const parts: string[] = [];

  const name = plan?.campaign_name || "Campaign";
  parts.push(`# ${name} — Campaign Brief`);
  parts.push(`_Generated by CampaignForge Multi-Agent AI Engine_\n`);

  if (plan?.big_idea) parts.push(`> **Big Idea:** ${plan.big_idea}\n`);

  if (campaign?.research) {
    parts.push("---\n## Market Research\n");
    parts.push(campaign.research);
  }
  if (campaign?.trends) {
    parts.push("\n---\n## Trend Analysis\n");
    parts.push(campaign.trends);
  }
  if (campaign?.strategy) {
    parts.push("\n---\n## Campaign Strategy\n");
    parts.push(campaign.strategy);
  }
  if (campaign?.content) {
    parts.push("\n---\n## Creative Content\n");
    parts.push(campaign.content);
  }
  if (campaign?.report) {
    parts.push("\n---\n## Executive Report\n");
    parts.push(campaign.report);
  }

  return parts.join("\n");
}

function buildPrintHTML(campaign: CampaignData | null, plan: PlanData | null): string {
  const name = plan?.campaign_name || "Campaign Brief";
  const sections: { title: string; content: string }[] = [];

  if (campaign?.report) sections.push({ title: "Executive Report", content: campaign.report });
  if (campaign?.research) sections.push({ title: "Market Research", content: campaign.research });
  if (campaign?.trends) sections.push({ title: "Trend Analysis", content: campaign.trends });
  if (campaign?.strategy) sections.push({ title: "Campaign Strategy", content: campaign.strategy });
  if (campaign?.content) sections.push({ title: "Creative Content", content: campaign.content });

  const renderSection = (s: { title: string; content: string }) => {
    const html = s.content
      .replace(/^### (.+)$/gm, '<h3 style="font-size:14px;font-weight:700;margin:16px 0 6px;color:#1a1a2e">$1</h3>')
      .replace(/^## (.+)$/gm, '<h2 style="font-size:16px;font-weight:700;margin:20px 0 8px;color:#1a1a2e;border-bottom:1px solid #e5e5e5;padding-bottom:6px">$1</h2>')
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/^- (.+)$/gm, '<li style="margin:2px 0;padding-left:4px">$1</li>')
      .replace(/\n/g, "<br>");
    return `<div style="margin-bottom:24px"><h1 style="font-size:18px;font-weight:800;color:#4f46e5;margin-bottom:12px">${s.title}</h1>${html}</div>`;
  };

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${name}</title>
<style>body{font-family:Inter,system-ui,sans-serif;max-width:800px;margin:0 auto;padding:40px 24px;color:#27272a;font-size:13px;line-height:1.7}
h1{page-break-after:avoid}@media print{body{padding:20px}}</style></head>
<body><div style="text-align:center;margin-bottom:32px;padding-bottom:20px;border-bottom:2px solid #4f46e5">
<h1 style="font-size:24px;font-weight:800;color:#1a1a2e;margin:0">${name}</h1>
${plan?.big_idea ? `<p style="font-size:14px;color:#71717a;font-style:italic;margin:8px 0 0">${plan.big_idea}</p>` : ""}
<p style="font-size:11px;color:#a1a1aa;margin:8px 0 0">Generated by CampaignForge &middot; ${new Date().toLocaleDateString()}</p>
</div>${sections.map(renderSection).join("<hr style='border:none;border-top:1px solid #e5e5e5;margin:24px 0'>")}</body></html>`;
}

export default function ExportPanel({ campaign, plan }: Props) {
  const [copied, setCopied] = useState(false);

  const handleCopyAll = () => {
    const md = buildMarkdown(campaign, plan);
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrintPDF = () => {
    const html = buildPrintHTML(campaign, plan);
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(html);
    w.document.close();
    setTimeout(() => w.print(), 400);
  };

  const hasContent = campaign && (campaign.research || campaign.content || campaign.report);
  if (!hasContent) return null;

  return (
    <div className="glass-card p-4 anim-fade-up">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileDown className="w-4 h-4 text-tx-3" />
          <h3 className="text-[12px] font-semibold text-tx-1 uppercase tracking-widest">
            Export Campaign
          </h3>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleCopyAll}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-edge text-[12px] font-medium text-tx-2 hover:text-tx-0 hover:border-edge-b hover:bg-surface-2/40 transition-all cursor-pointer"
          >
            {copied ? <ClipboardCheck className="w-3.5 h-3.5 text-ok" /> : <Clipboard className="w-3.5 h-3.5" />}
            {copied ? "Copied!" : "Copy Markdown"}
          </button>
          <button
            onClick={handlePrintPDF}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-[12px] font-semibold text-white bg-gradient-to-r from-indigo-600 to-violet-600 hover:brightness-110 shadow-md shadow-indigo-500/15 transition-all cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            Print / Save PDF
          </button>
        </div>
      </div>
    </div>
  );
}
