"use client";

import { useState } from "react";
import type { CampaignData, PlanData } from "@/app/page";
import { FileDown, ClipboardCheck, Clipboard, Printer, Download, Globe, Link, Check } from "lucide-react";

interface Props {
  campaign: CampaignData | null;
  plan: PlanData | null;
  onLocalize?: () => void;
}

/* ------------------------------------------------------------------ */
/*  Markdown builder                                                   */
/* ------------------------------------------------------------------ */

function buildMarkdown(campaign: CampaignData | null, plan: PlanData | null): string {
  const parts: string[] = [];
  const name = plan?.campaign_name || "Campaign";

  parts.push(`# ${name} — Campaign Brief`);
  parts.push(`_Generated by CampaignForge Multi-Agent AI Engine_\n`);
  if (plan?.big_idea) parts.push(`> **Big Idea:** ${plan.big_idea}\n`);

  if (campaign?.research) { parts.push("---\n## Market Research\n"); parts.push(campaign.research); }
  if (campaign?.trends) { parts.push("\n---\n## Trend Analysis\n"); parts.push(campaign.trends); }
  if (campaign?.strategy) { parts.push("\n---\n## Campaign Strategy\n"); parts.push(campaign.strategy); }
  if (campaign?.content) { parts.push("\n---\n## Creative Content\n"); parts.push(campaign.content); }
  if (campaign?.report) { parts.push("\n---\n## Executive Report\n"); parts.push(campaign.report); }

  return parts.join("\n");
}

/* ------------------------------------------------------------------ */
/*  HTML builder for print / PDF                                       */
/* ------------------------------------------------------------------ */

function buildPrintHTML(campaign: CampaignData | null, plan: PlanData | null): string {
  const name = plan?.campaign_name || "Campaign Brief";
  const sections: { title: string; content: string }[] = [];

  if (campaign?.report) sections.push({ title: "Executive Report", content: campaign.report });
  if (campaign?.research) sections.push({ title: "Market Research", content: campaign.research });
  if (campaign?.trends) sections.push({ title: "Trend Analysis", content: campaign.trends });
  if (campaign?.strategy) sections.push({ title: "Campaign Strategy", content: campaign.strategy });
  if (campaign?.content) sections.push({ title: "Creative Content", content: campaign.content });

  const renderSection = (s: { title: string; content: string }) => {
    const html = s.content
      .replace(/^### (.+)$/gm, '<h3 style="font-size:14px;font-weight:700;margin:16px 0 6px;color:#1a1a2e">$1</h3>')
      .replace(/^## (.+)$/gm, '<h2 style="font-size:16px;font-weight:700;margin:20px 0 8px;color:#1a1a2e;border-bottom:1px solid #e5e5e5;padding-bottom:6px">$1</h2>')
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/^- (.+)$/gm, '<li style="margin:2px 0;padding-left:4px">$1</li>')
      .replace(/\n/g, "<br>");
    return `<div style="margin-bottom:24px"><h1 style="font-size:18px;font-weight:800;color:#4f46e5;margin-bottom:12px">${s.title}</h1>${html}</div>`;
  };

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${name}</title>
<style>
  body{font-family:Inter,system-ui,sans-serif;max-width:800px;margin:0 auto;padding:40px 24px;color:#27272a;font-size:13px;line-height:1.7}
  h1{page-break-after:avoid}
  @media print{body{padding:20px}.no-print{display:none}}
  .print-btn{position:fixed;top:16px;right:16px;padding:10px 20px;background:#4f46e5;color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer}
</style></head>
<body>
<button class="print-btn no-print" onclick="window.print()">Print / Save PDF</button>
<div style="text-align:center;margin-bottom:32px;padding-bottom:20px;border-bottom:2px solid #4f46e5">
  <h1 style="font-size:24px;font-weight:800;color:#1a1a2e;margin:0">${name}</h1>
  ${plan?.big_idea ? `<p style="font-size:14px;color:#71717a;font-style:italic;margin:8px 0 0">${plan.big_idea}</p>` : ""}
  <p style="font-size:11px;color:#a1a1aa;margin:8px 0 0">Generated by CampaignForge &middot; ${new Date().toLocaleDateString()}</p>
</div>
${sections.map(renderSection).join("<hr style='border:none;border-top:1px solid #e5e5e5;margin:24px 0'>")}
</body></html>`;
}

/* ------------------------------------------------------------------ */
/*  Print via hidden iframe — avoids popup blocker                     */
/* ------------------------------------------------------------------ */

function printViaIframe(html: string) {
  const iframe = document.createElement("iframe");
  iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:none;visibility:hidden;";
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) { document.body.removeChild(iframe); return; }

  doc.open();
  doc.write(html);
  doc.close();

  // Wait for resources to load then print
  const tryPrint = () => {
    try {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    } catch { /* safari fallback */ }
    // Clean up after print dialog
    setTimeout(() => {
      try { document.body.removeChild(iframe); } catch { /* */ }
    }, 2000);
  };

  if (iframe.contentDocument?.readyState === "complete") {
    tryPrint();
  } else {
    iframe.onload = tryPrint;
    // Fallback timeout
    setTimeout(tryPrint, 800);
  }
}

/* ------------------------------------------------------------------ */
/*  Download as .md file                                               */
/* ------------------------------------------------------------------ */

function downloadMarkdown(campaign: CampaignData | null, plan: PlanData | null) {
  const md = buildMarkdown(campaign, plan);
  const name = (plan?.campaign_name || "campaign").replace(/[^\w\s-]/g, "").trim().slice(0, 50);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export default function ExportPanel({ campaign, plan, onLocalize }: Props) {
  const [copied, setCopied] = useState(false);
  const [shareLoading, setShareLoading] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [shareCopied, setShareCopied] = useState(false);

  const handleCopyAll = () => {
    const md = buildMarkdown(campaign, plan);
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrintPDF = () => {
    const html = buildPrintHTML(campaign, plan);
    printViaIframe(html);
  };

  const handleDownloadMd = () => {
    downloadMarkdown(campaign, plan);
  };

  const handleShare = async () => {
    if (shareUrl) {
      navigator.clipboard.writeText(window.location.origin + shareUrl);
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 2000);
      return;
    }
    setShareLoading(true);
    try {
      const res = await fetch("/api/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ campaign, plan }),
      });
      if (!res.ok) throw new Error("Failed");
      const data = await res.json();
      setShareUrl(data.url);
      navigator.clipboard.writeText(window.location.origin + data.url);
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 2500);
    } catch { /* silent */ } finally {
      setShareLoading(false);
    }
  };

  const hasContent = campaign && (campaign.research || campaign.content || campaign.report);
  if (!hasContent) return null;

  return (
    <div className="glass-card p-4 anim-fade-up">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-2">
          <FileDown className="w-4 h-4 text-tx-2" />
          <h3 className="text-[12px] font-semibold text-tx-1 uppercase tracking-widest">
            Export Campaign
          </h3>
        </div>
        <div className="flex flex-wrap gap-2">
          {/* Copy markdown */}
          <button
            onClick={handleCopyAll}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-edge text-[12px] font-medium text-tx-2 hover:text-tx-0 hover:border-edge-b hover:bg-surface-2/40 transition-all cursor-pointer"
          >
            {copied ? <ClipboardCheck className="w-3.5 h-3.5 text-ok" /> : <Clipboard className="w-3.5 h-3.5" />}
            {copied ? "Copied!" : "Copy Markdown"}
          </button>

          {/* Download .md */}
          <button
            onClick={handleDownloadMd}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-edge text-[12px] font-medium text-tx-2 hover:text-tx-0 hover:border-edge-b hover:bg-surface-2/40 transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            Download .md
          </button>

          {/* Localize */}
          {onLocalize && (
            <button
              onClick={onLocalize}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-edge text-[12px] font-medium text-tx-2 hover:text-tx-0 hover:border-edge-b hover:bg-surface-2/40 transition-all cursor-pointer"
            >
              <Globe className="w-3.5 h-3.5" />
              Localize
            </button>
          )}

          {/* Share link */}
          <button
            onClick={handleShare}
            disabled={shareLoading}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-edge text-[12px] font-medium text-tx-2 hover:text-tx-0 hover:border-edge-b hover:bg-surface-2/40 transition-all cursor-pointer disabled:opacity-50"
          >
            {shareCopied ? <Check className="w-3.5 h-3.5 text-ok" /> : <Link className="w-3.5 h-3.5" />}
            {shareCopied ? "Link copied!" : shareUrl ? "Copy link" : shareLoading ? "Sharing..." : "Share link"}
          </button>

          {/* Print / Save PDF */}
          <button
            onClick={handlePrintPDF}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-[12px] font-semibold text-white bg-gradient-to-r from-indigo-600 to-violet-600 hover:brightness-110 shadow-md shadow-indigo-500/15 transition-all cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            Print / Save PDF
          </button>
        </div>
      </div>
    </div>
  );
}
